sudo: required
dist: trusty
services: docker
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::12}
  - RELEASE_VERS=latest

before_install:
   - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
jobs:
  include:
    - stage: build
      script:
      - make build/base-notebook -t "${RELEASE_VERS}"
      - make build/python-notebook -t "${RELEASE_VERS}"
      - make build/datascience-notebook -t "${RELEASE_VERS}"
      - make build/dgx1-notebook -t "${RELEASE_VERS}"
    - stage: test, deploy
      script:
      - make test/base-notebook -t "${RELEASE_VERS}"
      - make push/base-notebook -t "${RELEASE_VERS}"
    - stage: test, deploy
      script:
      - make test/python-notebook -t "${RELEASE_VERS}"
      - make push/python-notebook -t "${RELEASE_VERS}"
    - stage: test, deploy
      script:
      - make test/datascience-notebook -t "${RELEASE_VERS}"
      - make push/datascience-notebook -t "${RELEASE_VERS}"
    - stage: test, deploy
      script:
      - make test/dgx1-notebook -t "${RELEASE_VERS}"
      - make push/dgx1-notebook -t "${RELEASE_VERS}"

notifications:
  slack: raz-s:se1PurXsQJv03nBZa9XWMOOS
