sudo: required
dist: trusty
services: docker
stages:
  - name: base_notebook
    if: commit_message =~ /\[(base|all)\]/
  - name: datascience_notebook
    if: commit_message =~ /\[(data|all)\]/
  - name: dgx1_notebook
    if: commit_message =~ /\[dgx|all\]/
  - name: python_notebook
    if: commit_message =~ /\[(py|all)\]/
  - name: r_notebook
    if: commit_message =~ /\[(r|all)\]/
  - name: sme_notebook
    if: commit_message =~ /\[(sme|all)\]/
  - name: statistics_notebook
    if: commit_message =~ /\[(stats|all)\]/
  - name: tensorflow_notebook
    if: commit_message =~ /\[(tensor|all)\]/
  - name: thin_notebook
    if: commit_message =~ /\[(python|all)\]/
  - name: deploy_all
    if: commit_message =~ /\[deploy-all\]/

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::12}
  - RELEASE_VERS=latest
  - DEV_VERS=dev
  - secure: PICm4yJOlywFyntG/Te3D7YoRIzSWvjhWgy1cDlDFxO3spghmatu2H1mEkkgnwvp+TKRlojT5GNEH3ihWRxxtqcFZC/FCUjJwxlOb/t9C1gdj3QVIvALV6IFf96eAGv7B9NCgErAnKyiOV7A7Lu1q9CwJ6ImBo8CGzNU6mAcRyGD4Is3wOD5HxXziUM3OVRutONQPfXXhNmt55OUMPBe3heCrMN1yaERlhy2QR35Uir5zC9ZFYq4C4oy0siDErRgVAm6Lv3qySz4tGebkMw7ToYRxJ2WdrImywqYgTwcOnR8bsWI6EfaxIeZWpK1d21VqG/SxrJXkYfA4hzK5KWVtoxZ54GOePUoIquKkYRoZ7ABOXZDoVKLeDGzVAGk6veiD8gs0hsC5tnI2KX3e00xDruIhfa+yquHOnNXPcm+Xu58r+pmyfnc9nuJfO61Y00GBCDsdFPnG/y608dLUadghTwGOoYxslLQtztJTHGUBK9yblnW/OvYz9H8dh/qAvWH0/jkj2vetFE3CyrTiShztBtZosu5UWUiEMAfgMSB9d2w3/W+S3N9O+5qSJ+pYK6zf43lcm2riTyxdVkZlZYZii+Znuq6xBwBMwyZdcrxK37LmMYx45O+qsWkBMcz51ryCpicqM4SY17xY8LpXMaxea7ld47kXCDLhkZxUrU0cmc=
  - secure: m5+SLMV5xjvUx8p/Bq9RpytyYHh7k/rDz+AnefU1/eJ20Q66RYb94ANzBg8fiv5PpnLgLfgKneXiG4+woNUZXOZntnnYTUw4PTfLCZc4c4Lea0ef+sM0FvGPA3a1o3DI/94yMC20sfXNNU/ZouGs1DPo63V4zSP3RBIGNXInpbiYUlJq83mgAAxWWKHDBybIJbtTgCYU05DugvID4e0thVqhVwIi+cK9YGneA8/wg8XtBicRs2l7ny5QO1PDXJjPzdrT2bha8HsGWFoAnQ5bef43NpRMrXU7KJ4BKgxH/QNg8IO+OntSI4ANZyOB94Q43zWipsx6L1nwhs0G4EfnfFFs1MbBNafWDgsc18qGEmSUfCHmAyTuUdbfTjFwCCF4rj5eomiYnnA2aXcj7SqeGMm6Czpu1Z5OZ4172h5qPDLmVMumuW8dQbklN/Ejo95TsArB2VRHqGwUX3W5sx74k2ocaRW2rNJBHGR28YAtKjAnSSn8x7DrTHRNIb+YQtl1C6VgZ1Shs9nG8z6CtReAvOTh+puMTDEOrt13XTF0uFj97EjnoO5sRz/rYo91Yf4PPdFgVPuvfvoZYdwvscbP+Lxr/BtJZHr0LUErd+Zj8Lw224ZR5Ox996o3y7bTHVYonbegAQOyUCus+OJrSX8f1cMUvnSga2ADadD88VG9o58=
before_script:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
jobs:
  include:
  - stage: base_notebook
    script:
      - make test/base-notebook
      - make build/base-notebook TAG="${RELEASE_VERS}"
      - make build/base-notebook TAG="${COMMIT}"
      - make push/base-notebook TAG="${RELEASE_VERS}"
      - make push/base-notebook TAG="${COMMIT}"
  - stage: datascience_notebook
    script:
      - make test/datascience-notebook
      - make build/datascience-notebook TAG="${RELEASE_VERS}"
      - make build/datascience-notebook TAG="${COMMIT}"
      - make push/datascience-notebook TAG="${RELEASE_VERS}"
      - make push/datascience-notebook TAG="${COMMIT}"
  - stage: dgx1_notebook
    script:
      - make test/dgx1-notebook
      - make build/dgx1-notebook TAG="${RELEASE_VERS}"
      - make build/dgx1-notebook TAG="${COMMIT}"
      - make push/dgx1-notebook TAG="${RELEASE_VERS}"
      - make push/dgx1-notebook TAG="${COMMIT}"
  - stage: python_notebook
    script:
      - make test/python-notebook
      - make build/python-notebook TAG="${RELEASE_VERS}"
      - make build/python-notebook TAG="${COMMIT}"
      - make push/python-notebook TAG="${RELEASE_VERS}"
      - make push/python-notebook TAG="${COMMIT}"
  - stage: r_notebook
    script:
      - make test/r-notebook
      - make build/r-notebook TAG="${RELEASE_VERS}"
      - make build/r-notebook TAG="${COMMIT}"
      - make push/r-notebook TAG="${RELEASE_VERS}"
      - make push/r-notebook TAG="${COMMIT}"
  - stage: sme_notebook
    script:
      - make test/sme-notebook
      - make build/sme-notebook TAG="${RELEASE_VERS}"
      - make build/sme-notebook TAG="${COMMIT}"
      - make push/sme-notebook TAG="${RELEASE_VERS}"
      - make push/sme-notebook TAG="${COMMIT}"
  - stage: statistics_notebook
    script:
      - make test/statistics-notebook
      - make build/statistics-notebook TAG="${RELEASE_VERS}"
      - make build/statistics-notebook TAG="${COMMIT}"
      - make push/statistics-notebook TAG="${RELEASE_VERS}"
      - make push/statistics-notebook TAG="${COMMIT}"
  - stage: tensorflow_notebook
    script:
      - make test/tensorflow-notebook
      - make build/tensorflow-notebook TAG="${RELEASE_VERS}"
      - make build/tensorflow-notebook TAG="${COMMIT}"
      - make push/tensorflow-notebook TAG="${RELEASE_VERS}"
      - make push/tensorflow-notebook TAG="${COMMIT}"
  - stage: thin_notebook
    script:
      - make test/thin-notebook
      - make build/thin-notebook TAG="${RELEASE_VERS}"
      - make build/thin-notebook TAG="${COMMIT}"
      - make push/thin-notebook TAG="${RELEASE_VERS}"
      - make push/thin-notebook TAG="${COMMIT}"
  - stage: deploy_all
    script:
      - python3 configure.py -t "${DEV_VERS}"
      - make test-all TAG="${DEV_VERS}"
      - make build-all TAG="${RELEASE_VERS}"
      - make build-all TAG="${COMMIT}"
      - make push-all TAG="${RELEASE_VERS}"
      - make push-all TAG="${COMMIT}"

notifications:
  slack: raz-s:se1PurXsQJv03nBZa9XWMOOS
